#!/bin/bash
#SBATCH --job-name=bea_03_dos
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --partition=compute

# Generated by VASP-Doctor BE-A (slurm profile).
# 本脚本仅为生成产物；提交由用户在集群上手动执行：sbatch submit.sh

srun vasp_std
