"""KpointsGenerator（设计文档 7.6/10.6 节）。

两种模式：
- 均匀网格（automatic_density）：由 ``generate_kpoint_grid`` 的确定性结果渲染；
- band line-mode：高对称路径由 pymatgen ``HighSymmKpath`` 给出（flag 控制启用），
  按 VASP Line-mode 官方格式渲染（四行头 + 逐段端点对 + 段间空行），保证确定性。

只生成文件文本，不执行任何 VASP/命令。
"""

from __future__ import annotations

import math
from typing import Any, Dict, List, Optional, Sequence, Tuple

from backend.app.recipes.errors import KpointsGenerationFailed
from backend.app.schemas.generation import KpointsSpec

VALID_CENTERINGS = ("Gamma", "Monkhorst")


def _fmt(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    # 负零与空字符串归一为 "0"，避免渲染出 "-0" 或 ""。
    if text in ("", "-0"):
        return "0"
    return text


def _finite_coord(value: Any, label: str) -> float:
    """高对称点坐标标量校验：拒绝 bool、字符串/字节、None、NaN 与 ±Inf。

    pymatgen 返回的坐标元素可能是 numpy 标量（如 ``np.float64``），
    因此不用 ``isinstance(value, (int, float))`` 判定类型，而是先排除
    明确非法类型（bool/str/bytes/None）再转 float；float() 失败即 fail closed。
    NaN 能绕过普通大小比较，必须显式 isfinite。
    """

    if isinstance(value, bool) or isinstance(value, (str, bytes, bytearray)):
        raise KpointsGenerationFailed(
            f"high-symmetry coordinate for {label!r} must be a finite number, "
            f"got {value!r}",
            details={"label": str(label), "value": repr(value)},
        )
    try:
        number = float(value)
    except (TypeError, ValueError) as exc:
        raise KpointsGenerationFailed(
            f"high-symmetry coordinate for {label!r} must be a finite number, "
            f"got {value!r}",
            details={"label": str(label), "value": repr(value)},
        ) from exc
    if not math.isfinite(number):
        raise KpointsGenerationFailed(
            f"high-symmetry coordinate for {label!r} must be a finite number, "
            f"got {number!r}",
            details={"label": str(label), "value": repr(number)},
        )
    return number


class KpointsGenerator:
    def generate(self, spec: KpointsSpec, comment: str = "Generated by BE-A") -> str:
        if spec.mode == "automatic_density":
            return self.uniform(spec.grid, spec.centering, comment=comment, kppa=spec.kppa)
        if spec.mode == "line_mode":
            raise KpointsGenerationFailed(
                "line_mode requires a structure; call line_mode() explicitly",
                details={"mode": spec.mode},
            )
        raise KpointsGenerationFailed(
            f"unknown kpoints mode: {spec.mode}", details={"mode": spec.mode}
        )

    def uniform(
        self,
        grid: Optional[Sequence[int]],
        centering: Optional[str] = None,
        comment: str = "Generated by BE-A",
        kppa: Optional[float] = None,
    ) -> str:
        if not grid or len(grid) != 3 or any(int(n) < 1 for n in grid):
            raise KpointsGenerationFailed(
                f"invalid uniform grid: {grid!r}", details={"grid": list(grid or [])}
            )
        center = centering or "Gamma"
        if center not in VALID_CENTERINGS:
            raise KpointsGenerationFailed(
                f"unknown centering: {center}", details={"centering": center}
            )
        mesh_label = "Gamma" if center == "Gamma" else "Monkhorst-Pack"
        header = comment
        if kppa is not None:
            header = f"{comment} (kppa={_fmt(float(kppa))})"
        lines = [
            header,
            "0",
            mesh_label,
            f"{int(grid[0])} {int(grid[1])} {int(grid[2])}",
            "0 0 0",
        ]
        return "\n".join(lines) + "\n"

    def line_mode(
        self,
        poscar_text: str,
        divisions: int = 60,
        comment: str = "Line-mode band path generated by BE-A",
    ) -> str:
        """pymatgen HighSymmKpath → VASP Line-mode 文本（四行头 + 端点对）。"""

        if isinstance(divisions, bool) or not isinstance(divisions, int) or divisions < 1:
            raise KpointsGenerationFailed(
                f"invalid line-mode divisions: {divisions!r}",
                details={"divisions": repr(divisions)},
            )
        try:
            from pymatgen.io.vasp import Poscar

            try:  # pymatgen 新版（≥2024）HighSymmKpath 位于 bandstructure
                from pymatgen.symmetry.bandstructure import HighSymmKpath
            except ImportError:  # pragma: no cover - 旧版回退
                from pymatgen.symmetry.kpath import HighSymmKpath
        except ImportError as exc:  # pragma: no cover - 依赖缺失环境
            raise KpointsGenerationFailed(
                f"pymatgen unavailable for band path: {exc}", details={"reason": str(exc)}
            ) from exc
        try:
            poscar = (
                Poscar.from_str(poscar_text)
                if hasattr(Poscar, "from_str")
                else Poscar.from_string(poscar_text)
            )
            structure = poscar.structure
            kpath = HighSymmKpath(structure)
        except Exception as exc:  # noqa: BLE001
            raise KpointsGenerationFailed(
                f"failed to derive high-symmetry path: {exc}",
                details={"reason": str(exc)},
            ) from exc
        return self._render_line_mode(kpath, divisions, comment)

    def _extract_kpath(self, kpath: Any) -> Tuple[List[List[str]], Dict[str, Any]]:
        """从 pymatgen HighSymmKpath 的三种历史形态提取 (segments, 坐标映射)。

        坐标保留原始值，由 ``_endpoint_line`` 逐项做有限性校验（fail closed）。
        """

        raw = getattr(kpath, "kpath", None)
        if isinstance(raw, dict):  # pymatgen 新版：{"path": [...], "kpoints": {...}}
            segments = raw.get("path")
            coord_map = raw.get("kpoints")
        elif raw is not None:
            segments = raw
            coord_map = getattr(kpath, "kpoints", None)
        else:  # pragma: no cover - 旧版 pymatgen
            segments = getattr(kpath, "path", None)
            coord_map = getattr(kpath, "kpoints", None)
        if not isinstance(coord_map, dict):
            raise KpointsGenerationFailed(
                "high-symmetry path provides no kpoints coordinate mapping",
                details={"reason": "missing kpoints mapping"},
            )
        if segments is None:
            raise KpointsGenerationFailed(
                "high-symmetry path provides no path segments",
                details={"reason": "missing path"},
            )
        if not isinstance(segments, (list, tuple)):
            raise KpointsGenerationFailed(
                f"high-symmetry path must be a sequence of segments, got {segments!r}",
                details={"reason": "path is not a sequence"},
            )
        path: List[List[str]] = []
        for segment in segments:
            if not isinstance(segment, (list, tuple)):
                raise KpointsGenerationFailed(
                    f"high-symmetry path segment must be a sequence of labels, "
                    f"got {segment!r}",
                    details={"reason": "segment is not a sequence"},
                )
            path.append([str(label) for label in segment])
        return path, dict(coord_map)

    def _endpoint_line(self, label: str, kpoints: Dict[str, Any]) -> str:
        coords = kpoints.get(label)
        if coords is None:
            raise KpointsGenerationFailed(
                f"high-symmetry label {label!r} has no coordinates in the path mapping",
                details={"label": label, "available": sorted(kpoints)},
            )
        # 坐标容器兼容 list/tuple/numpy array（pymatgen 实际返回 ndarray）。
        if (isinstance(coords, (str, bytes, bytearray)) or not hasattr(coords, "__len__")
                or len(coords) != 3):
            raise KpointsGenerationFailed(
                f"high-symmetry coordinates for {label!r} must be exactly 3 values, "
                f"got {coords!r}",
                details={"label": label, "coords": repr(coords)},
            )
        x, y, z = (_finite_coord(value, label) for value in coords)
        return f"{_fmt(x)} {_fmt(y)} {_fmt(z)}  ! {self._normalize_label(label)}"

    def _render_line_mode(
        self, kpath: Any, divisions: int, comment: str
    ) -> str:
        """渲染 VASP Line-mode 文本。

        头部固定四行：``comment / divisions / Line-mode / Reciprocal``；
        正文为端点对：连续链 A-B-C 展开为 (A,B)、(B,C)，
        对与对之间恰一个空行（``Reciprocal`` 与首对之间无空行），单个 ``\\n`` 结尾。
        pymatgen 返回异常路径数据时 fail closed，绝不渲染残缺 KPOINTS。
        """

        path, kpoints = self._extract_kpath(kpath)
        if not path:
            raise KpointsGenerationFailed(
                "high-symmetry path is empty",
                details={"reason": "empty path"},
            )
        lines: List[str] = [comment, f"{int(divisions)}", "Line-mode", "Reciprocal"]
        first_pair = True
        for segment in path:
            if len(segment) < 2:
                raise KpointsGenerationFailed(
                    "high-symmetry path segment must contain at least 2 labels to "
                    f"form an endpoint pair, got {segment!r}",
                    details={"segment": list(segment)},
                )
            for start, end in zip(segment, segment[1:]):
                if not first_pair:
                    lines.append("")
                first_pair = False
                lines.append(self._endpoint_line(start, kpoints))
                lines.append(self._endpoint_line(end, kpoints))
        return "\n".join(lines) + "\n"

    @staticmethod
    def _normalize_label(label: str) -> str:
        """将 pymatgen 标签（如 ``\\Gamma``、``\\Sigma_1``）规范化为纯文本。"""

        cleaned = label.replace("\\", "").strip()
        if cleaned.lower() == "gamma":
            return "GAMMA"
        return cleaned
