"""KpointsGenerator（设计文档 7.6/10.6 节）。

两种模式：
- 均匀网格（automatic_density）：由 ``generate_kpoint_grid`` 的确定性结果渲染；
- band line-mode：高对称路径由 pymatgen ``HighSymmKpath`` 给出（flag 控制启用），
  文本渲染为固定格式，保证确定性。

只生成文件文本，不执行任何 VASP/命令。
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence

from backend.app.recipes.errors import KpointsGenerationFailed
from backend.app.schemas.generation import KpointsSpec

VALID_CENTERINGS = ("Gamma", "Monkhorst")


def _fmt(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".") or "0"


class KpointsGenerator:
    def generate(self, spec: KpointsSpec, comment: str = "Generated by BE-A") -> str:
        if spec.mode == "automatic_density":
            return self.uniform(spec.grid, spec.centering, comment=comment, kppa=spec.kppa)
        if spec.mode == "line_mode":
            raise KpointsGenerationFailed(
                "line_mode requires a structure; call line_mode() explicitly",
                details={"mode": spec.mode},
            )
        raise KpointsGenerationFailed(
            f"unknown kpoints mode: {spec.mode}", details={"mode": spec.mode}
        )

    def uniform(
        self,
        grid: Optional[Sequence[int]],
        centering: Optional[str] = None,
        comment: str = "Generated by BE-A",
        kppa: Optional[float] = None,
    ) -> str:
        if not grid or len(grid) != 3 or any(int(n) < 1 for n in grid):
            raise KpointsGenerationFailed(
                f"invalid uniform grid: {grid!r}", details={"grid": list(grid or [])}
            )
        center = centering or "Gamma"
        if center not in VALID_CENTERINGS:
            raise KpointsGenerationFailed(
                f"unknown centering: {center}", details={"centering": center}
            )
        mesh_label = "Gamma" if center == "Gamma" else "Monkhorst-Pack"
        header = comment
        if kppa is not None:
            header = f"{comment} (kppa={_fmt(float(kppa))})"
        lines = [
            header,
            "0",
            mesh_label,
            f"{int(grid[0])} {int(grid[1])} {int(grid[2])}",
            "0 0 0",
        ]
        return "\n".join(lines) + "\n"

    def line_mode(
        self,
        poscar_text: str,
        divisions: int = 60,
        comment: str = "Line-mode band path generated by BE-A",
    ) -> str:
        """pymatgen HighSymmKpath → 固定格式 line-mode 文本。"""

        try:
            from pymatgen.io.vasp import Poscar

            try:  # pymatgen 新版（≥2024）HighSymmKpath 位于 bandstructure
                from pymatgen.symmetry.bandstructure import HighSymmKpath
            except ImportError:  # pragma: no cover - 旧版回退
                from pymatgen.symmetry.kpath import HighSymmKpath
        except ImportError as exc:  # pragma: no cover - 依赖缺失环境
            raise KpointsGenerationFailed(
                f"pymatgen unavailable for band path: {exc}", details={"reason": str(exc)}
            ) from exc
        try:
            poscar = (
                Poscar.from_str(poscar_text)
                if hasattr(Poscar, "from_str")
                else Poscar.from_string(poscar_text)
            )
            structure = poscar.structure
            kpath = HighSymmKpath(structure)
        except Exception as exc:  # noqa: BLE001
            raise KpointsGenerationFailed(
                f"failed to derive high-symmetry path: {exc}",
                details={"reason": str(exc)},
            ) from exc
        return self._render_line_mode(kpath, divisions, comment)

    def _render_line_mode(
        self, kpath: Any, divisions: int, comment: str
    ) -> str:
        raw = getattr(kpath, "kpath", None)
        if isinstance(raw, dict):  # pymatgen 新版：{"path": [...], "kpoints": {...}}
            path: List[List[str]] = [list(segment) for segment in raw["path"]]
            kpoints: Dict[str, List[float]] = {
                label: [float(v) for v in coords] for label, coords in raw["kpoints"].items()
            }
        elif raw is not None:
            path = [list(segment) for segment in raw]
            kpoints = {label: [float(v) for v in coords] for label, coords in kpath.kpoints.items()}
        else:  # pragma: no cover - 旧版 pymatgen
            path = [list(segment) for segment in kpath.path]
            kpoints = {label: [float(v) for v in coords] for label, coords in kpath.kpoints.items()}
        lines = [comment, f"{divisions}", "Reciprocal"]
        for segment_index, segment in enumerate(path):
            if segment_index > 0:
                lines.append("")
            for label in segment:
                coords = kpoints[label]
                shown = self._normalize_label(label)
                lines.append(
                    f"{_fmt(coords[0])} {_fmt(coords[1])} {_fmt(coords[2])}  ! {shown}"
                )
        return "\n".join(lines) + "\n"

    @staticmethod
    def _normalize_label(label: str) -> str:
        """将 pymatgen 标签（如 ``\\Gamma``、``\\Sigma_1``）规范化为纯文本。"""

        cleaned = label.replace("\\", "").strip()
        if cleaned.lower() == "gamma":
            return "GAMMA"
        return cleaned
