// 从 formatters 重新导出枚举映射供其他模块使用
import {
  SEVERITY_MAP,
  WORKFLOW_STATUS_MAP,
  DIAGNOSIS_STATUS_MAP,
  HPC_JOB_STATUS_MAP,
  DEPLOYMENT_STATUS_MAP,
} from '../types/enums';

export { SEVERITY_MAP, WORKFLOW_STATUS_MAP, DIAGNOSIS_STATUS_MAP, HPC_JOB_STATUS_MAP, DEPLOYMENT_STATUS_MAP };