#!/bin/bash
# Generic run script（无调度系统指令；适用于本地/手动运行场景）
# Generated by VASP-Doctor BE-A (generic profile).
# 运行方式：sh submit.sh  # 手动提交
set -euo pipefail

# 资源说明（仅记录，不强制执行）：nodes=1, tasks_per_node=1, walltime=12:00:00

mpirun -np 1 vasp_std
