"""PP-00 offline feasibility probe, not a production post-processing parser.

Reads explicitly supplied fixtures only. Does not contact any service or read
POTCAR. XML reference arrays are extracted independently with ElementTree.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import importlib.metadata
import json
from pathlib import Path
import platform
import tempfile
import warnings
import xml.etree.ElementTree as ET

import numpy as np
from pymatgen.electronic_structure.core import Spin
from pymatgen.io.vasp import outputs
from pymatgen.io.vasp.inputs import Incar, Kpoints


def xml_probe(path: Path) -> dict:
    raw = path.read_bytes()
    xml = gzip.decompress(raw)
    root = ET.fromstring(xml)
    with warnings.catch_warnings(record=True) as caught:
        parsed = outputs.Vasprun(
            path, parse_dos=True, parse_eigen=True,
            parse_projected_eigen=False, parse_potcar_file=False,
            exception_on_bad_xml=True,
        )
    checked, max_error = 0, 0.0

    def same(actual, expected):
        nonlocal checked, max_error
        a, b = np.asarray(actual), np.asarray(expected)
        assert a.shape == b.shape, (a.shape, b.shape)
        assert np.isfinite(a).all() and np.isfinite(b).all()
        np.testing.assert_allclose(a, b, rtol=0, atol=1e-10)
        checked += a.size
        max_error = max(max_error, float(np.max(np.abs(a - b), initial=0)))

    dos = root.findall('.//dos')[-1]
    same(parsed.efermi, float(dos.find("i[@name='efermi']").text))
    total_sets = dos.findall('total/array/set/set')
    assert total_sets, 'Fixture must contain total DOS'
    for index, node in enumerate(total_sets):
        spin = Spin.up if index == 0 else Spin.down
        rows = np.array([[float(x) for x in r.text.split()] for r in node.findall('r')])
        same(parsed.tdos.energies, rows[:, 0])
        same(parsed.tdos.densities[spin], rows[:, 1])
        same(parsed.idos.densities[spin], rows[:, 2])

    partial = dos.find('partial/array')
    projected_values = 0
    if partial is not None:
        fields = [n.text.strip() for n in partial.findall('field')][1:]
        for atom_index, atom_node in enumerate(partial.findall('set/set')):
            for spin_index, node in enumerate(atom_node.findall('set')):
                spin = Spin.up if spin_index == 0 else Spin.down
                rows = np.array([[float(x) for x in r.text.split()] for r in node.findall('r')])
                orbitals = list(parsed.pdos[atom_index])
                assert len(orbitals) == len(fields)
                for orbital_index, orbital in enumerate(orbitals):
                    same(parsed.pdos[atom_index][orbital][spin], rows[:, orbital_index + 1])
                    projected_values += rows.shape[0]

    eigen_sets = root.findall('.//eigenvalues/array/set')[-1].findall('set')
    for index, node in enumerate(eigen_sets):
        spin = Spin.up if index == 0 else Spin.down
        expected = [[[float(x) for x in r.text.split()] for r in k.findall('r')]
                    for k in node.findall('set')]
        same(parsed.eigenvalues[spin], expected)
    kpoints = root.find("kpoints/varray[@name='kpointlist']")
    same(parsed.actual_kpoints, [[float(x) for x in row.text.split()] for row in kpoints])
    return {
        'sample': path.name, 'compressed_sha256': hashlib.sha256(raw).hexdigest(),
        'compressed_bytes': len(raw), 'xml_bytes': len(xml),
        'is_spin': parsed.is_spin, 'kpoints': len(parsed.actual_kpoints),
        'dos_points': len(parsed.tdos.energies),
        'eigenvalue_shapes': {str(k): list(v.shape) for k, v in parsed.eigenvalues.items()},
        'compared_scalars': checked, 'projected_dos_scalars': projected_values,
        'max_absolute_error': max_error, 'efermi_ev': parsed.efermi,
        'warning_types': sorted({type(w.message).__name__ for w in caught}),
        'scope': 'parser/reference agreement; not a validation of original calculation',
    }


def synthetic_probes(root: Path) -> dict:
    # Deliberately hand-written independent values, never generated by pymatgen.
    directory = root / '中文 路径'
    directory.mkdir()
    prefix = ' 1 1 1 1\nunused\nunused\nunused\nsynthetic\n 2 2 2\n'
    first = '\n 0.0 0.0 0.0 0.5\n 1 -1.0 2.0\n 2 2.0 0.0\n'
    second = '\n 0.5 0.0 0.0 0.5\n 1 -0.5 2.0\n 2 3.0 0.0\n'
    good = directory / 'EIGENVAL'
    good.write_text(prefix + first + second, encoding='utf-8')
    eigen = outputs.Eigenval(good)
    np.testing.assert_array_equal(eigen.eigenvalues[Spin.up][:, :, 0], [[-1, 2], [-.5, 3]])
    truncated = directory / 'EIGENVAL.truncated'
    truncated.write_text(prefix + first, encoding='utf-8')
    try:
        result = outputs.Eigenval(truncated)
        missing_rejected = False
        actual = len(result.kpoints)
    except Exception:
        missing_rejected, actual = True, None

    # Volume=8 A^3; charge grid values average to 4.5 electrons per cell.
    charge = directory / 'CHGCAR'
    charge.write_text('synthetic\n1\n2 0 0\n0 2 0\n0 0 2\nH\n1\nDirect\n0 0 0\n\n2 2 2\n1 2 3 4 5 6 7 8\n', encoding='utf-8')
    density = outputs.Chgcar.from_file(charge)
    np.testing.assert_array_equal(density.data['total'].flatten(order='F'), np.arange(1, 9))
    np.testing.assert_allclose(density.structure.volume, 8, rtol=0, atol=1e-12)
    np.testing.assert_allclose(density.data['total'].mean(), 4.5, rtol=0, atol=1e-12)
    # Two equal-density half-components give zero difference on this fixed grid.
    diff = density.data['total'] - density.data['total'] / 2 - density.data['total'] / 2
    np.testing.assert_array_equal(diff, np.zeros((2, 2, 2)))
    return {
        'unicode_path_eigenval': 'passed', 'charge_grid_order_and_integral': 'passed',
        'same_grid_difference_arithmetic': 'passed (synthetic only)',
        'eigenval_truncation': {'library_rejected': missing_rejected,
                              'declared_kpoints': 2, 'actual_kpoints': actual,
                              'product_requirement': 'explicit count/shape/finite validation required'},
        'charge_limit': 'not real CHGCAR performance or PAW restart validation',
    }


def local_probe(directory: Path) -> dict:
    # Local private fixture is summarized only, never copied or exported.
    eigen_path = directory / 'EIGENVAL'
    eigen = outputs.Eigenval(eigen_path)
    kpoints = Kpoints.from_file(directory / 'KPOINTS')
    incar = Incar.from_file(directory / 'INCAR')
    dos_path = directory / 'DOSCAR'
    with dos_path.open(encoding='utf-8') as file:
        ions = int(file.readline().split()[0])
        for _ in range(4):
            file.readline()
        info = file.readline().split()
        nedos, efermi = int(info[2]), float(info[3])
        rows = np.array([[float(v) for v in file.readline().split()] for _ in range(nedos)])
    assert rows.shape[1] == (5 if incar.get('ISPIN', 1) == 2 else 3)
    assert np.isfinite(rows).all() and (np.diff(rows[:, 0]) > 0).all()
    return {'id': 'existing-local-test1-ok', 'not_redistributed': True,
            'doscar_bytes': dos_path.stat().st_size, 'ions': ions, 'dos_points': nedos,
            'dos_columns': rows.shape[1], 'efermi_ev': efermi, 'ispin': eigen.ispin,
            'kpoints_mode': str(kpoints.style), 'nkpoints': eigen.nkpt, 'nbands': eigen.nbands,
            'dos_sha256': hashlib.sha256(dos_path.read_bytes()).hexdigest(),
            'band_path_eligible': kpoints.style == Kpoints.supported_modes.Line_mode,
            'scope': 'layout/metadata and Eigenval feasibility only; not a path-band reference'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--fixtures', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--local-sample', type=Path)
    args = parser.parse_args()
    manifest = json.loads((args.fixtures / 'manifest.json').read_text(encoding='utf-8'))
    for item in manifest['files']:
        assert hashlib.sha256((args.fixtures / item['name']).read_bytes()).hexdigest() == item['sha256']
    report = {'python': platform.python_version(),
              'versions': {k: importlib.metadata.version(k) for k in ('pymatgen','numpy','matplotlib')},
              'vasp_doscar_class_available': hasattr(outputs, 'Doscar'),
              'upstream_commit': manifest['commit'],
              'xml_probes': [xml_probe(args.fixtures / item['name']) for item in manifest['files']
                             if item['name'].endswith('.xml.gz')]}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='pp00-', dir=args.output.parent) as temporary:
        report['synthetic_probes'] = synthetic_probes(Path(temporary))
    if args.local_sample:
        report['local_probe'] = local_probe(args.local_sample)
    args.output.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
